apiVersion: v1
kind: ConfigMap
metadata:
  name: geometry-config
  namespace: geometry-system
data:
  authorized-users.json: |
    {
      "0x0000000000000000000000000000000000000000": {
        "role": "genesis",
        "added": "2026-02-16"
      }
    }
